import type { Config } from "@netlify/functions";
import { getStore } from "@netlify/blobs";
import { createHmac, timingSafeEqual } from "node:crypto";

// Zoom webhook receiver — fires automatically when a cloud recording finishes
// processing. Pipeline:
//   1. Verify the request came from Zoom (signature + freshness check)
//   2. Handle url_validation handshake on the FIRST request (URL setup)
//   3. On recording.completed: match the meeting to a client+program, pull
//      the transcript, drop it on the program as a session note, run an AI
//      summary in Phoebe's voice, and queue the polished version for her
//      review on the home page.
//
// Configure in Zoom Marketplace → Server-to-Server OAuth app → Feature →
// Event Subscriptions:
//   - Endpoint URL: https://hub.phoebeblamey.com.au/api/zoom-webhook
//   - Events: recording.completed (and optionally meeting.ended)
//   - Set ZOOM_VERIFICATION_TOKEN env var to the Secret Token from this page

// ── Phoebe voice for the AI summary (server-side mirror of PHOEBE_VOICE) ──
// Kept identical to the browser-side constant in index.html so summaries
// generated by the webhook flow read the same as ones Phoebe triggers
// manually from the client detail page.
const PHOEBE_VOICE =
  "Voice and style — write as if Phoebe Blamey wrote it herself.\n" +
  "- Australian English. organise / prioritise / colour / cosy. Not US spellings.\n" +
  "- Warm, direct, conversational. No corporate jargon. NEVER use: leverage, synergy, ecosystem, robust, unlock, level up, game-changer, deep-dive (as a verb), deliverables, KPIs unless quoting.\n" +
  "- Smart, real, empowering. She's a financial expert + business coach but speaks like a mate at a kitchen table — not a consultant.\n" +
  "- Short sentences. Plain words. Specific over abstract. \"$5k month\" not \"meaningful revenue increase\".\n" +
  "- Speak TO the client in second person (\"you\"). Refer to Phoebe as \"Phoebe\" or \"I\" depending on context — never \"the coach\" or \"your coach\".\n" +
  "- Australian dates: 8 May 2026, never 5/8/2026. Times: 9:30am / 2:00pm.\n" +
  "- Currency: AUD with $ prefix.\n" +
  "- Direct without being harsh. \"Your pricing is leaving money on the table\" not \"You're not optimising your pricing strategy\".\n" +
  "- No padding, no diplomatic softening, no \"I hope this helps\" sign-offs.\n" +
  "- Sign-off (when needed): \"Phoebe x\".";

export default async (req: Request) => {
  if (req.method !== "POST") return new Response("Method not allowed", { status: 405 });

  const verToken = Netlify.env.get("ZOOM_VERIFICATION_TOKEN") || "";

  // We need the raw body for signature verification AND for parsing.
  // Zoom's signature is over the raw bytes of the request body.
  const rawBody = await req.text();
  let payload: any = {};
  try { payload = JSON.parse(rawBody || "{}"); } catch { return new Response("Bad JSON", { status: 400 }); }

  // ── 1. Zoom URL validation handshake ─────────────────────────────────────
  // First request Zoom sends to a new endpoint:
  //   { event: "endpoint.url_validation", payload: { plainToken } }
  // Expected response:
  //   { plainToken, encryptedToken: HMAC-SHA256(plainToken, verToken) }
  if (payload.event === "endpoint.url_validation" && payload.payload?.plainToken) {
    if (!verToken) {
      console.error("[zoom-webhook] URL validation called but ZOOM_VERIFICATION_TOKEN env var is missing");
      return new Response(JSON.stringify({ error: "Server not configured: ZOOM_VERIFICATION_TOKEN missing" }), { status: 503 });
    }
    const plain = String(payload.payload.plainToken);
    const encrypted = createHmac("sha256", verToken).update(plain).digest("hex");
    return new Response(JSON.stringify({ plainToken: plain, encryptedToken: encrypted }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  // ── 2. Signature verification on real events ────────────────────────────
  // Zoom signs every event with HMAC-SHA256:
  //   message    = "v0:{x-zm-request-timestamp}:{rawBody}"
  //   signature  = "v0=" + hex(HMAC-SHA256(verToken, message))
  // The signature lives in the x-zm-signature header. Reject anything that
  // doesn't match — otherwise an attacker could forge events.
  // Skip verification entirely if no token is configured (dev mode), but log.
  if (verToken) {
    const sigHeader = req.headers.get("x-zm-signature") || "";
    const tsHeader  = req.headers.get("x-zm-request-timestamp") || "";
    if (!sigHeader || !tsHeader) {
      console.warn("[zoom-webhook] event missing signature headers, rejecting");
      return new Response(JSON.stringify({ error: "Missing signature headers" }), { status: 401 });
    }
    // Reject events older than 5 minutes (replay defence)
    const tsNum = parseInt(tsHeader, 10);
    if (!Number.isFinite(tsNum) || Math.abs(Date.now() - tsNum) > 5 * 60 * 1000) {
      console.warn("[zoom-webhook] event timestamp out of window:", tsHeader);
      return new Response(JSON.stringify({ error: "Stale or invalid timestamp" }), { status: 401 });
    }
    const message = `v0:${tsHeader}:${rawBody}`;
    const expectedHex = createHmac("sha256", verToken).update(message).digest("hex");
    const expectedSig = `v0=${expectedHex}`;
    // Constant-time compare
    let matches = false;
    try {
      const a = Buffer.from(sigHeader);
      const b = Buffer.from(expectedSig);
      matches = a.length === b.length && timingSafeEqual(a, b);
    } catch {}
    if (!matches) {
      console.warn("[zoom-webhook] signature mismatch — rejecting");
      return new Response(JSON.stringify({ error: "Invalid signature" }), { status: 401 });
    }
  } else {
    console.warn("[zoom-webhook] ZOOM_VERIFICATION_TOKEN not set — skipping signature verification");
  }

  // ── 3. Branch by event type ─────────────────────────────────────────────
  const eventType: string = payload.event || "";
  if (eventType !== "recording.completed") {
    // ack other events — we don't act on them but Zoom needs a 200 to stop retrying
    return new Response(JSON.stringify({ received: true, ignored: eventType }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  const meeting = payload.payload?.object;
  if (!meeting) return new Response("No meeting payload", { status: 400 });

  const startTime: string = meeting.start_time || "";
  const topic: string = meeting.topic || "";
  const meetingId: string = String(meeting.id || meeting.uuid || "");
  const hostEmail: string = (meeting.host_email || "").toLowerCase();
  const duration: number = meeting.duration || 0;

  // ── 4. Match the meeting to a client + program ──────────────────────────
  // Strategy: name-in-topic AND date proximity (±1 day). Both required so
  // we don't false-match — better to leave it for manual assignment than
  // attach to the wrong client.
  const store = getStore("clients");
  const list = await store.list();
  let matchedClient: any = null;
  let matchedProg: any = null;

  for (const blob of list.blobs) {
    if (!blob.key) continue;
    const raw = await store.get(blob.key);
    if (!raw) continue;
    let client: any;
    try { client = JSON.parse(raw); } catch { continue; }
    if (client.archived) continue;
    if (!client.name) continue;

    // Topic must contain the client's first name (case-insensitive)
    const firstName = String(client.name).split(" ")[0];
    if (!firstName) continue;
    const nameInTopic = topic.toLowerCase().includes(firstName.toLowerCase());
    if (!nameInTopic) continue;

    // Find a program whose sessionDate is within ±1 day of the recording
    if (!startTime) continue;
    const recT = new Date(startTime).getTime();
    const closestProg = (client.programs || [])
      .filter((p: any) => p && p.sessionDate)
      .sort((a: any, b: any) => Math.abs(new Date(a.sessionDate).getTime() - recT) - Math.abs(new Date(b.sessionDate).getTime() - recT))[0];
    if (!closestProg) continue;
    const sd = new Date(closestProg.sessionDate).getTime();
    if (Math.abs(recT - sd) > 86400000) continue;

    matchedClient = client;
    matchedProg = closestProg;
    break;
  }

  if (!matchedClient) {
    return new Response(JSON.stringify({
      received: true,
      matched: false,
      reason: "No client matched on first-name-in-topic + date proximity",
      meeting: { id: meetingId, topic, startTime, duration, hostEmail },
    }), { status: 200, headers: { "Content-Type": "application/json" } });
  }

  // ── 5. Pull transcript via Zoom API directly (avoids internal HTTP hop) ─
  let accessToken = "";
  const accountId    = Netlify.env.get("ZOOM_ACCOUNT_ID");
  const zoomClientId = Netlify.env.get("ZOOM_CLIENT_ID");
  const zoomSecret   = Netlify.env.get("ZOOM_CLIENT_SECRET");
  if (!accountId || !zoomClientId || !zoomSecret) {
    return ack200({ received: true, matched: true, transcriptError: "Zoom credentials not configured" });
  }
  try {
    const tokenResp = await fetch(
      `https://zoom.us/oauth/token?grant_type=account_credentials&account_id=${accountId}`,
      {
        method: "POST",
        headers: {
          "Authorization": "Basic " + btoa(`${zoomClientId}:${zoomSecret}`),
          "Content-Type":  "application/x-www-form-urlencoded",
        },
      }
    );
    const tokenData: any = await tokenResp.json();
    accessToken = tokenData.access_token;
    if (!accessToken) throw new Error("No access token");
  } catch (err: any) {
    return ack200({ received: true, matched: true, transcriptError: "Zoom auth failed: " + String(err?.message || err) });
  }

  // The recording.completed payload usually includes recording_files inline,
  // so we don't strictly need a separate fetch. But fall back to /recordings
  // if the inline files are missing.
  let recordingFiles: any[] = Array.isArray(meeting.recording_files) ? meeting.recording_files : [];
  if (!recordingFiles.length) {
    try {
      const r = await fetch(`https://api.zoom.us/v2/meetings/${encodeURIComponent(meetingId)}/recordings`, {
        headers: { "Authorization": `Bearer ${accessToken}` },
      });
      if (r.ok) {
        const j: any = await r.json();
        recordingFiles = j.recording_files || [];
      }
    } catch {}
  }

  const transcriptFile = recordingFiles.find((f: any) =>
    f.file_type === "TRANSCRIPT" || f.file_extension === "VTT" || f.recording_type === "audio_transcript"
  );
  const videoFile = recordingFiles.find((f: any) => f.file_type === "MP4");

  let transcriptText = "";
  if (transcriptFile && transcriptFile.download_url) {
    try {
      const txResp = await fetch(transcriptFile.download_url + "?access_token=" + accessToken);
      const raw = await txResp.text();
      transcriptText = raw
        .split("\n")
        .filter((line: string) => {
          const trimmed = line.trim();
          return trimmed
            && !trimmed.startsWith("WEBVTT")
            && !/^\d+$/.test(trimmed)
            && !/^\d{2}:\d{2}:\d{2}/.test(trimmed)
            && !/^NOTE/.test(trimmed)
            && !trimmed.startsWith("<");
        })
        .join(" ")
        .replace(/\s+/g, " ")
        .trim();
    } catch (err: any) {
      console.error("[zoom-webhook] transcript download failed:", err?.message || err);
    }
  }

  // ── 6. Drop a session note on the matched program with the transcript ───
  matchedProg.sessionNotes = matchedProg.sessionNotes || [];
  const noteId = `sn-zoom-${Date.now()}`;
  const sessionDate = startTime ? startTime.split("T")[0] : new Date().toISOString().split("T")[0];

  // ── MDC auto-tag: compute sprint+week from cohort.start vs session date.
  // Phoebe asked for this — the manual "tag this Zoom to Sprint X / Week Y"
  // step shouldn't be needed when the system can work it out itself.
  // 24-week MDC = 4 sprints × 6 weeks. Week-of-cohort = floor(daysSinceStart / 7) + 1.
  let autoSprint: number | undefined;
  let autoWeek: number | undefined;
  try {
    if (matchedProg.workbook === "mdc" && matchedProg.cohort && startTime) {
      const cohortsStore = getStore("cohorts");
      const cohortsRaw = await cohortsStore.get("cohorts");
      if (cohortsRaw) {
        const cohortsArr = JSON.parse(cohortsRaw) || [];
        const co = (Array.isArray(cohortsArr) ? cohortsArr : []).find((c: any) => c && c.id === matchedProg.cohort);
        if (co && co.start) {
          const startDay = new Date(co.start).getTime();
          const sessionDay = new Date(startTime).getTime();
          const daysSince = Math.floor((sessionDay - startDay) / 86400000);
          if (daysSince >= 0 && daysSince < 24 * 7) {
            const weekOfCohort = Math.floor(daysSince / 7) + 1; // 1..24
            autoSprint = Math.ceil(weekOfCohort / 6);           // 1..4
            autoWeek   = ((weekOfCohort - 1) % 6) + 1;          // 1..6
          }
        }
      }
    }
  } catch (err: any) {
    console.warn("[zoom-webhook] auto-sprint compute failed:", err?.message || err);
  }

  const newNote: any = {
    id: noteId,
    date: sessionDate,
    text: `[Zoom: ${topic}] — auto-pulled by webhook (${transcriptText.length} chars)`,
    zoomMeetingId: meetingId,
    zoomTopic: topic,
    zoomTranscript: transcriptText,
    zoomUrl: meeting.share_url || "",
    zoomVideoUrl: (videoFile && (videoFile.play_url || videoFile.download_url)) || "",
    zoomPasscode: meeting.recording_play_passcode || "",
    zoomDuration: duration,
    hasTranscript: !!transcriptText,
    sharedWithClient: false,
    aiSummaryStatus: transcriptText ? "queued" : "no-transcript",
    autoSource: "zoom-webhook",
    createdAt: new Date().toISOString(),
    ...(autoSprint && autoWeek ? { sprint: autoSprint, week: autoWeek, autoTagged: true } : {}),
  };
  matchedProg.sessionNotes.push(newNote);

  // ── MDC sprint/week auto-advance — bump program's mdcSprint/mdcWeek to
  // match the latest auto-tagged session, mirroring the client-side
  // autoAdvanceMdcProgress() logic. So the moment a Zoom is webhooked,
  // the client sees the new week's pane on next portal load.
  if (autoSprint && autoWeek && matchedProg.workbook === "mdc") {
    const curSprint = matchedProg.mdcSprint || 1;
    const curWeek   = matchedProg.mdcWeek || 1;
    if (autoSprint > curSprint || (autoSprint === curSprint && autoWeek > curWeek)) {
      matchedProg.mdcSprint = autoSprint;
      matchedProg.mdcWeek   = autoWeek;
    }
  }

  matchedClient.updatedAt = new Date().toISOString();
  matchedClient.lastTouched = new Date().toISOString();

  // ── 7. AI summary in Phoebe's voice (queues for her review) ─────────────
  // Skipped if there's no transcript yet or no Anthropic key configured.
  if (transcriptText && transcriptText.length > 200) {
    const apiKey = Netlify.env.get("ANTHROPIC_API_KEY");
    if (apiKey) {
      try {
        const summaryPrompt =
          PHOEBE_VOICE + "\n\n────────────\n\n" +
          "You are Phoebe Blamey's editor. Below is a raw Zoom transcript from a coaching session with " +
          (matchedClient.name || "a client") + (matchedClient.biz ? " (" + matchedClient.biz + ")" : "") +
          ". Turn it into a polished, client-facing session summary.\n\n" +
          "Structure (use these exact headings):\n" +
          "## What we covered\n" +
          "## Your wins this session\n" +
          "## Action items for you\n" +
          "## What I'm sitting with\n\n" +
          "Strip filler, half-sentences and the noise of real speech. Keep specifics: numbers, names, deadlines. Maximum 400 words total.\n\n" +
          "TRANSCRIPT:\n" + transcriptText.slice(0, 18000);
        const aiResp = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": apiKey,
            "anthropic-version": "2023-06-01",
          },
          body: JSON.stringify({
            model: "claude-sonnet-4-6",
            max_tokens: 1500,
            messages: [{ role: "user", content: summaryPrompt }],
          }),
        });
        if (aiResp.ok) {
          const aiData: any = await aiResp.json();
          let summaryText = "";
          if (Array.isArray(aiData.content)) {
            aiData.content.forEach((b: any) => { if (b && b.type === "text" && b.text) summaryText += b.text; });
          }
          if (summaryText.trim()) {
            newNote.aiSummary = summaryText.trim();
            newNote.aiSummaryStatus = "pending-review";
            newNote.aiSummaryGeneratedAt = new Date().toISOString();
          } else {
            newNote.aiSummaryStatus = "error";
            newNote.aiSummaryError = "Empty AI response";
          }
        } else {
          newNote.aiSummaryStatus = "error";
          newNote.aiSummaryError = "AI call failed: " + aiResp.status;
        }
      } catch (err: any) {
        newNote.aiSummaryStatus = "error";
        newNote.aiSummaryError = String(err?.message || err);
      }
    } else {
      newNote.aiSummaryStatus = "queued"; // can be retried manually from the UI
    }
  }

  // ── 8. Save the updated client back to Netlify Blobs ────────────────────
  try {
    await store.set(matchedClient.id, JSON.stringify(matchedClient));
  } catch (err: any) {
    console.error("[zoom-webhook] failed to save client:", err?.message || err);
    return ack200({ received: true, matched: true, saveError: String(err?.message || err) });
  }

  // ── 9. Push to the activity log so it appears on Phoebe's home pulse ────
  try {
    const baseUrl = (Netlify.env.get("URL") || "https://hub.phoebeblamey.com.au").replace(/\/$/, "");
    fetch(`${baseUrl}/api/activity-log`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        append: {
          id: `act-${Date.now()}`,
          ts: new Date().toISOString(),
          kind: "transcript",
          icon: "🎬",
          title: `Auto-pulled Zoom · ${matchedClient.name}`,
          clientId: matchedClient.id,
          clientName: matchedClient.name,
          progId: matchedProg.id,
          detail: `${topic} · ${duration} min · ${newNote.aiSummaryStatus === "pending-review" ? "AI summary ready for review" : newNote.aiSummaryStatus}`,
        },
      }),
    }).catch(() => {});
  } catch {}

  return ack200({
    received: true,
    matched: true,
    clientId: matchedClient.id,
    clientName: matchedClient.name,
    progId: matchedProg.id,
    transcript: !!transcriptText,
    aiSummary: newNote.aiSummaryStatus,
  });
};

function ack200(body: any) {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

export const config: Config = {
  path: "/api/zoom-webhook",
};
